services:
    pwn:
        container_name: pwn_test
        image: hah4/pwndocker:latest
        build: 
            context: .
            dockerfile: Dockerfile
        security_opt:
            - seccomp:unconfined
        cap_add:
            - SYS_PTRACE
        volumes:
            - ./binaries:/pwn/binaries
        ports:
            - "23946:23946"
